### ISSUE TITLE
ValueError: only one element tensors can be converted to Python scalars

### ISSUE THREAD

**Issue by MinSongKi** [jd730/OICR-pytorch#16]
I simply run the trainval_net.py demo script (from GitHub) like so:

Traceback (most recent call last):
  File "/home/OICR-pytorch/lib/model/oicr/oicr.py", line 71, in forward
    nb = int(num_boxes[:,0].item())
ValueError: only one element tensors can be converted to Python scalars

During handling of the above exception, another exception occurred:

**Comment by jd730** [comment]
Hi, did you run the below script?
```
CUDA_VISIBLE_DEVICES=0  python3 trainval_net.py --dataset pascal_voc --net vgg16 \
   --bs 1 --nw 6 --save_dir='results/test_single'  \
   --lr 0.001 --cuda --disp_interval 50 --vis \
	--checkpoint_interval=500 --model='oicr' --threshold=0.1
```

it seems that num_boxes[:,0].item() has some array or tuple. Could you print num_boxes[:,0]? 
Also could you tell me the batch size?

**Comment by MinSongKi** [comment]
Thanks very much, but another error like so:

raceback (most recent call last):
  File "/home/cvpr-ku/OICR-pytorch/trainval_net.py", line 419, in <module>
    rois, midn_loss, oc1, oc2, oc3, cls_prob= OICR(im_data, im_rois, labels, num_boxes)
  File "/home/cvpr-ku/.conda/envs/oicr_py/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cvpr-ku/.conda/envs/oicr_py/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 114, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/cvpr-ku/.conda/envs/oicr_py/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 124, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/cvpr-ku/.conda/envs/oicr_py/lib/python3.5/site-packages/torch/nn/parallel/parallel_apply.py", line 65, in parallel_apply
    raise output
  File "/home/cvpr-ku/.conda/envs/oicr_py/lib/python3.5/site-packages/torch/nn/parallel/parallel_apply.py", line 41, in _worker
    output = module(*input, **kwargs)
  File "/home/cvpr-ku/.conda/envs/oicr_py/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cvpr-ku/OICR-pytorch/lib/model/oicr/oicr.py", line 89, in forward
    base_feat = self.OICR_base(im_data)
  File "/home/cvpr-ku/.conda/envs/oicr_py/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cvpr-ku/.conda/envs/oicr_py/lib/python3.5/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/cvpr-ku/.conda/envs/oicr_py/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cvpr-ku/.conda/envs/oicr_py/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f9bf5776390>>
Traceback (most recent call last):
  File "/home/cvpr-ku/.conda/envs/oicr_py/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 349, in __del__
  File "/home/cvpr-ku/.conda/envs/oicr_py/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 328, in _shutdown_workers
  File "/home/cvpr-ku/.conda/envs/oicr_py/lib/python3.5/multiprocessing/queues.py", line 337, in get
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable

**Comment by jd730** [comment]
Could you tell me your run script? It seems that you are using multi-GPU but some parameters are mismatch (such as batch_size).

print each input before https://github.com/jd730/OICR-pytorch/blob/580f6efd5ad0d993b8226cd8d486ec8ed44de1f6/trainval_net.py#L417

**Comment by MinSongKi** [comment]
안녕하세요!

한국 분이신 것 같아서 다시 메일 드립니다.

우선 gpu가 2개이고, 파라미터는 gpu 2, bs 2로 설정하여 아래와 같이 진행을 했습니다.

   - CUDA_VISIBLE_DEVICES=0,1 python3 trainval_net.py --dataset pascal_voc
   --net vgg16 --bs 2 -nw 4 --save_dir='output' --model='oicr'

말씀하신대로 input을 출력해보았는데 im_rois가 아래와 같은 형태로 출력되는데 좌표면 R X 4형태가 되어야하는 것이
아닌가요..?
[image: image.png]

*바쁘신데 답변 주셔서 감사합니다!*



<kms2014@yonsei.ac.kr>


2020년 2월 3일 (월) 오후 4:53, Jaedong Hwang <notifications@github.com>님이 작성:

**Comment by jd730** [comment]
@MinSongKi , 
Unfortunately,  I cannot see your image. The reason why you have a trouble is that batch_size is divided into two in here to follow original Caffe implementation. However, the `run.sh` seems to not consider this fact. 

I apologize for the inconvenience and will upload new `run.sh` soon.

If you change your batch size as 4 or make delete below line, it will work.

https://github.com/jd730/OICR-pytorch/blob/580f6efd5ad0d993b8226cd8d486ec8ed44de1f6/trainval_net.py#L252

**Comment by jd730** [comment]
@MinSongKi  Hi, did you solve the problem?

**Comment by jd730** [comment]
`bs 4` worked.

**Comment by MinSongKi** [comment]
Hello,

No.. bs 4 also not worked.

Another error has occurred.
RuntimeError: invalid argument 0: Sizes of tensors must match except in
dimension 0
<https://forums.fast.ai/t/runtimeerror-invalid-argument-0-sizes-of-tensors-must-match-except-in-dimension-0/33274>.
Got 640 and 576 in dimension 2 at..
*-----------------------------------------------------------------------------*


*Minsong Ki (Ph.D Course) *Dept. Computer Science
Computer Vision&Pattern Recognition lab

Office: +82-2-2123-3876
Mobile: +82-10-5870-0505
Email: kms2014@yonsei.ac.kr




2020년 2월 10일 (월) 오전 7:46, Jaedong Hwang <notifications@github.com>님이 작성:

**Comment by jd730** [comment]
Hi, 
I am sorry that I found version mismatch between my local and Github.
The reason why `bs 4` does not work is my `collate_fn` works when `bs` is larger than 6. 

Also, could you use `--mGPUs` flag which turns on DataParallel. your script does not have that flag and it will make an error you mentioned first again (`ValueError: only one element tensors can be converted to Python scalars`)
