### ISSUE TITLE
categories index uniform

### ISSUE THREAD

**Issue by XuanX-new** [jd730/OICR-pytorch#30]
Hello, sorry to disturb you.I replaced the data of voc2007 with my own data, and the following problems occurred.

Traceback (most recent call last):
  File "trainval_net.py", line 418, in <module>
    data = next(data_iter)
  File "trainval_net.py", line 382, in cycle
    for x in it :
  File "/home/summer/anaconda3/envs/oicr/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/summer/anaconda3/envs/oicr/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/summer/anaconda3/envs/oicr/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/summer/anaconda3/envs/oicr/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/summer/zkdcd/OICR-pytorch-master/lib/roi_data_layer/roibatchLoader.py", line 44, in __getitem__
    blobs = get_minibatch(minibatch_db, self._num_classes)
  File "/home/summer/zkdcd/OICR-pytorch-master/lib/roi_data_layer/minibatch.py", line 58, in get_minibatch
    labels_blob = np.vstack((labels_blob, labels))
  File "<__array_function__ internals>", line 6, in vstack
  File "/home/summer/anaconda3/envs/oicr/lib/python3.6/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 20 and the array at index 1 has size 10

It should be because the categories are not uniform. My data category is 10 categories. But I have been looking for a reason for a long time. No place to modify the category was found. Can you give some suggestions for modification.
Thank you.

**Comment by jd730** [comment]
Hi, I guess referring to https://github.com/jd730/OICR-pytorch/blob/bcfe9cd2d7ab77fc46bc031da8fd27bd9971d57d/trainval_net.py#L262 might be helpful. The batchloader takes num_class as an argument.

**Comment by XuanX-new** [comment]
Appreciate that . I have solved this problem just.
