### ISSUE TITLE
cannot compile 

### ISSUE THREAD

**Issue by ziyanyang** [jd730/OICR-pytorch#32]
Hi,

I'm trying to compile the lib. I have already installed pytorch==0.4.0, and all other required packages. I'm using conda virtual environment and using "module load cuda-toolkit-9.0 cudnn-7.0.5 gcc-5.5.0" to load corresponding cuda and gcc. However I got the error as:

: /zf18/zy3cx/OICR-pytorch/lib ; sh make.sh 
running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
Compiling nms kernels by nvcc...
Including CUDA code.
/net/zf18/zy3cx/OICR-pytorch/lib/model/nms
['/net/zf18/zy3cx/OICR-pytorch/lib/model/nms/src/nms_cuda_kernel.cu.o']
generating /tmp/tmpel2zqnk8/_nms.c
setting the current directory to '/tmp/tmpel2zqnk8'
running build_ext
building '_nms' extension
creating net
creating net/zf18
creating net/zf18/zy3cx
creating net/zf18/zy3cx/OICR-pytorch
creating net/zf18/zy3cx/OICR-pytorch/lib
creating net/zf18/zy3cx/OICR-pytorch/lib/model
creating net/zf18/zy3cx/OICR-pytorch/lib/model/nms
creating net/zf18/zy3cx/OICR-pytorch/lib/model/nms/src
/sw/centos/gcc/5.5.0/bin/gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA -I/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/zf18/zy3cx/ENTER/envs/py3pt0.3/include/python3.6m -c _nms.c -o ./_nms.o
In file included from /zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                 from _nms.c:570:
/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory
compilation terminated.
Traceback (most recent call last):
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command '/sw/centos/gcc/5.5.0/bin/gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command '/sw/centos/gcc/5.5.0/bin/gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 37, in <module>
    ffi.build()
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 184, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 108, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/cffi/api.py", line 727, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/cffi/recompiler.py", line 1565, in recompile
    compiler_verbose, debug)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: CompileError: command '/sw/centos/gcc/5.5.0/bin/gcc' failed with exit status 1
Compiling roi pooling kernels by nvcc...
/net/zf18/zy3cx/OICR-pytorch/lib/model/roi_pooling
Including CUDA code.
generating /tmp/tmp2ownhn6a/_roi_pooling.c
setting the current directory to '/tmp/tmp2ownhn6a'
running build_ext
building '_roi_pooling' extension
creating net
creating net/zf18
creating net/zf18/zy3cx
creating net/zf18/zy3cx/OICR-pytorch
creating net/zf18/zy3cx/OICR-pytorch/lib
creating net/zf18/zy3cx/OICR-pytorch/lib/model
creating net/zf18/zy3cx/OICR-pytorch/lib/model/roi_pooling
creating net/zf18/zy3cx/OICR-pytorch/lib/model/roi_pooling/src
/sw/centos/gcc/5.5.0/bin/gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA -I/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/zf18/zy3cx/ENTER/envs/py3pt0.3/include/python3.6m -c _roi_pooling.c -o ./_roi_pooling.o
In file included from /zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                 from _roi_pooling.c:570:
/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory
compilation terminated.
Traceback (most recent call last):
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command '/sw/centos/gcc/5.5.0/bin/gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command '/sw/centos/gcc/5.5.0/bin/gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 36, in <module>
    ffi.build()
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 184, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 108, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/cffi/api.py", line 727, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/cffi/recompiler.py", line 1565, in recompile
    compiler_verbose, debug)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: CompileError: command '/sw/centos/gcc/5.5.0/bin/gcc' failed with exit status 1
Compiling roi align kernels by nvcc...
/net/zf18/zy3cx/OICR-pytorch/lib/model/roi_align
Including CUDA code.
generating /tmp/tmpts8wp1dm/_roi_align.c
setting the current directory to '/tmp/tmpts8wp1dm'
running build_ext
building '_roi_align' extension
creating net
creating net/zf18
creating net/zf18/zy3cx
creating net/zf18/zy3cx/OICR-pytorch
creating net/zf18/zy3cx/OICR-pytorch/lib
creating net/zf18/zy3cx/OICR-pytorch/lib/model
creating net/zf18/zy3cx/OICR-pytorch/lib/model/roi_align
creating net/zf18/zy3cx/OICR-pytorch/lib/model/roi_align/src
/sw/centos/gcc/5.5.0/bin/gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA -I/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/zf18/zy3cx/ENTER/envs/py3pt0.3/include/python3.6m -c _roi_align.c -o ./_roi_align.o
In file included from /zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                 from _roi_align.c:570:
/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory
compilation terminated.
Traceback (most recent call last):
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command '/sw/centos/gcc/5.5.0/bin/gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command '/sw/centos/gcc/5.5.0/bin/gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 38, in <module>
    ffi.build()
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 184, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 108, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/cffi/api.py", line 727, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/cffi/recompiler.py", line 1565, in recompile
    compiler_verbose, debug)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: CompileError: command '/sw/centos/gcc/5.5.0/bin/gcc' failed with exit status 1
Compiling roi crop kernels by nvcc...
Including CUDA code.
/net/zf18/zy3cx/OICR-pytorch/lib/model/roi_crop
generating /tmp/tmpzgp95at6/_roi_crop.c
setting the current directory to '/tmp/tmpzgp95at6'
running build_ext
building '_roi_crop' extension
creating net
creating net/zf18
creating net/zf18/zy3cx
creating net/zf18/zy3cx/OICR-pytorch
creating net/zf18/zy3cx/OICR-pytorch/lib
creating net/zf18/zy3cx/OICR-pytorch/lib/model
creating net/zf18/zy3cx/OICR-pytorch/lib/model/roi_crop
creating net/zf18/zy3cx/OICR-pytorch/lib/model/roi_crop/src
/sw/centos/gcc/5.5.0/bin/gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA -I/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/zf18/zy3cx/ENTER/envs/py3pt0.3/include/python3.6m -c _roi_crop.c -o ./_roi_crop.o
In file included from /zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                 from _roi_crop.c:570:
/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory
compilation terminated.
Traceback (most recent call last):
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command '/sw/centos/gcc/5.5.0/bin/gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command '/sw/centos/gcc/5.5.0/bin/gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 36, in <module>
    ffi.build()
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 184, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 108, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/cffi/api.py", line 727, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/cffi/recompiler.py", line 1565, in recompile
    compiler_verbose, debug)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: CompileError: command '/sw/centos/gcc/5.5.0/bin/gcc' failed with exit status 1

I'm not sure how to fix it. Could you help me with it? Is it necessary to compile these libraries? Thanks!

Ziyan

**Comment by jd730** [comment]
Hi, the error seems that there is no cuda.h for some reasons. Did you install and set cuda correctly?

`/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory`

Also, could you tell me which GPU (e.g., Titan XP) are you using?

**Comment by ziyanyang** [comment]
> Hi, the error seems that there is no cuda.h for some reasons. Did you install and set cuda correctly?
> 
> `/zf18/zy3cx/ENTER/envs/py3pt0.3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory`
> 
> Also, could you tell me which GPU (e.g., Titan XP) are you using?

I'm using TITAN X (Pascal). But don't worry about this issue, I have fixed it by changing cuda path and compiled by:
CPATH=/my_cuda_path/9.0/include/ ./make.sh

**Comment by ziyanyang** [comment]
Also, in compilation, please check https://github.com/spack/spack/issues/6005 to set up the corresponding architecture. I'm using TITAN X (Pascal), and the architecture should be sm_61 instead of sm_52.

**Comment by jd730** [comment]
Thank @ziyanyang , I found that Titan X (Maxwell) is sm52 and Titan X (Pascal) is sm61 as you mentioned. I changed README.
